language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

script:
  - ./gradlew ":$MODULE:build"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
   matrix:
     - MODULE=android-runner
     - MODULE=core
     - MODULE=ddm-tools
     - MODULE=gradle-plugin

notifications:
  email: true

sudo: false

cache:
   directories:
        - $HOME/.gradle